version: '3.4'

services:
  webfrontend:
    image: ${DOCKER_REGISTRY-}webfrontend
    build:
      context: .
      dockerfile: WebFrontEnd/Dockerfile
    depends_on:
      - "webapi"

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile    
    environment:
      REDIS_CONN: "redis"
      DBServer: "mssql"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2020"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    container_name: mssql